setwd("C:\\rClass\\Exploratory")
file <- "./data/household_power_consumption.txt"
data <- read.table(file,sep=";",header=TRUE,na.strings="?")
data$Date2 <- as.Date(data$Date, "%d/%m/%Y")
data2 <- subset(data, Date2=="2007/2/1"|Date2=="2007/2/2")
png('Assignment1Plot4.png')
par(mfrow=c(2,2))
plot(data2$DateTime,as.numeric(as.character(data2$Global_active_power)),type='l',ylab="Global Active Power",main="Global Active Power",cex.lab=.75,cex.axis=.75,cex.main=.8,xlab = "")
plot(data2$DateTime,data2$Voltage,type="l",ylab="Voltage",xlab="datetime",cex.lab=.75,cex.axis=.75,cex.main=.8)
plot(data2$DateTime,data2$Sub_metering_1,type='l',ylab="Energy sub metering",main="",cex.lab=.75,cex.axis=.75,cex.main=.8,xlab = "")
lines(data2$DateTime,data2$Sub_metering_2,col="red")
lines(data2$DateTime,data2$Sub_metering_3,col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"),cex=0.75,bty = "n")
plot(data2$DateTime,data2$Global_reactive_power,type="l",ylab="Global_reactive_power",xlab="datetime",cex.lab=.75,cex.axis=.75,cex.main=.8)
dev.off()
